### ISSUE TITLE
 It may be required to uninstall the `cordova-plugin-compat` plugin due to multiple "BuildHelper" classes defined in dex files

### ISSUE THREAD

**Issue by janpio** [apache/cordova-mobile-spec#151]
(<https://stackoverflow.com/questions/46562289/multiple-dex-files-define-lorg-apache-cordova-buildhelper/46562523#46562523>)

(Issues title taken from this commit: https://github.com/apache/cordova-mobile-spec/commit/e4b0a23484332d44e4ff44c5eab0f7566a38d19c) 

Could you elaborate this quirk please @brodybits? Could not reproduce.

**Comment by brodybits** [comment]
I think this happened because I did not delete the existing `mobilespec` before running createmobilespec.js. This is why I raised the tip to delete `mobilespec` if it exists in #178.

This may be a "troubleshooting" item.

**Comment by brodybits** [comment]
This should not happen any more now that we removed `cordova-plugin-compat` (PR #182) and we added the caution message to <https://github.com/apache/cordova-mobile-spec/blob/master/createmobilespec/README.md#create-the-app>.
