### ISSUE TITLE
Cleanup or remove testing with third-party plugins

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-mobile-spec#171]
in <https://github.com/apache/cordova-mobile-spec/blob/8f8304fae6f8658dc783d1fa4d0bda4c95ef09b7/createmobilespec/createmobilespec.js#L151-L193>

Some things I can think of right now:
* plugins commented out would likely be outdated
* `CORDOVA_REGISTRY_PLUGINS` looks like it comes from an old registry
* `TELERIK_VERIFIED_PLUGINS` may have some outdated plugins
* `PLUGREG_PLUGINS` has a single plugin by myself that is definitely outdated

P.S. According to the comment in <https://github.com/apache/cordova-mobile-spec/pull/153/files#r236861171>, things are broken with third-party plugins in <https://github.com/apache/cordova-mobile-spec/blob/master/createmobilespec/createmobilespec.js#L143-L147>

I would now favor remove testing with third-party plugins, as discussed below.

**Comment by brodybits** [comment]
from review of #153

**Comment by janpio** [comment]
Afaik the Telerik Plugin registry also is no more.
What is/was plugreg?

The general concept of being able to test 3rd party plugins is still interesting, although I am not sure if in the concept of cordova-mobile-spec.

**Comment by brodybits** [comment]
> What is/was plugreg?

I think plugreg was a registry made 5-7 years ago, before PhoneGap Build was available and before Cordova was using npm. I think that plugreg is not used any more since npm gives us what we need.

I just requested confirmation in: <https://lists.apache.org/thread.html/d28d35869f70a39b4eb0be04a06f7c20e764d94976fe7f5c7070fde8@%3Cdev.cordova.apache.org%3E>

> The general concept of being able to test 3rd party plugins is still interesting, although I am not sure if in the concept of cordova-mobile-spec.

At this point I would favor getting rid of the 3rd party plugins, just changed the title to reflect this sentiment.

The comment in <https://github.com/apache/cordova-mobile-spec/pull/153/files#r236861171> that things with <https://github.com/apache/cordova-mobile-spec/blob/master/createmobilespec/createmobilespec.js#L143-L147> are broken makes me especially motivated to remove the third-party plugins from cordova-mobile-spec. I will add this info to the description for extra clarification.

**Comment by janpio** [comment]
Seems I did the research in parallel - replied with what I found on the thread ;)

**Comment by brodybits** [comment]
> > What is/was plugreg?
> 
> I think plugreg was a registry made 5-7 years ago, before PhoneGap Build was available and before Cordova was using npm. I think that plugreg is not used any more since npm gives us what we need.
> 
> I just requested confirmation in: [...]

Answer from @dpogue:
> plugreg was a 3rd party website displaying stats from the Cordova
> Plugin Registry (back before we used npm)

this was evidently not so clear to me before today

> Seems I did the research in parallel - replied with what I found on the thread ;)

with the following info which I am pasting here for the sake of extra clarity:

> * https://cordova.apache.org/news/2013/10/21/cordova-registry.html
> ✞ https://cordova.apache.org/news/2015/09/08/cpr-readonly.html

> Even more context:
https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html
