### ISSUE TITLE
Drop deprecated cordova-plugin-file-transfer testing

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-mobile-spec#184]
(which consistently gives me failures on Android)

~~this would invalidate <https://github.com/apache/cordova-labs/issues/16> - __Move cordova-filetransfer branch to cordova-plugin-file-transfer repo__~~

**Comment by janpio** [comment]
> this would invalidate apache/cordova-labs#16 - Move cordova-filetransfer branch to cordova-plugin-file-transfer repo

Not at all. This app is just one (mostly unused btw) way to run tests.

**Comment by brodybits** [comment]
> > this would invalidate [...]
>
> Not at all. [...]

Removed from description by strikeout. The original title and beginning of the description continue to stand on my part.

**Comment by janpio** [comment]
You having failures also is not a reason to drop a test tbh.
The plugin being deprecated might be - but that would be a different issue then and include more plugins.

**Comment by brodybits** [comment]
> The plugin being deprecated might be - but that would be a different issue then and include more plugins.

Closing now, in favor of a new issue that I am planning to raise later today.

<https://github.com/apache/cordova/issues/54#issuecomment-442834293>) indicates to me that using mobilespec with the `cordova-filetransfer` branch of `cordova-labs` is used for plugin testing, maybe primarily for plugin testing, maybe only for plugin testing. I was not aware of this information from recent emails and GitHub issues.
