### ISSUE TITLE
Consistent failures on Android

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-mobile-spec#195]
* file.spec.147 - consistently fails on Android
* cordova-plugin-file-transfer-tests.tests - multiple failures, consistently on Android
* cordova-plugin-media-tests - multiple failures, consistently on my Samsung Galaxy S6 device (seemed to work in the past)

**Comment by janpio** [comment]
`cordova-mobile-spec` only builds an app that can run these tests, the actual tests are part of the plugins. Please report these failures in individual issues there (and compare with CI of those repositories to check if this also affects the CI builds). Thanks.
